# docker-composerリファレンス和訳 
# https://qiita.com/zembutsu/items/9e9d80e05e36e882caaa
version: '2'

services:

  rails: &app_base
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    env_file:
      - "./.env.dev"
    volumes:
      - ".:/app"
    # 他のサービスやコンテナから全てマウントする
    volumes_from:
      - data
    ports:
      - "4000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    # 実行時に再起動するかどうか(今回はdockerをビルド時や立ち上げる際にMYSQLを再起動、という意味)
    restart: always
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes_from:
      - data
    ports:
      - "5306:3306"

  # dataコンテナを用いてmysql, gem, node_moduleなどをコンテナ内にキャッシュしておくことでbuild時の再インストールを防ぐ。
  data:
    image: "busybox"
    volumes:
      - db:/var/lib/mysql
      - bundle:/usr/local/bundle

volumes:
  db:
    driver: local
  bundle:
    driver: local
